name: first workflow # workflow run-name
on: workflow_dispatch # when the flow will trigger (workflow_dispatch - allow manually trigger flow)
jobs: #task your performing
  first-job: #task name
    runs-on: ubuntu-latest #runner where we are running flow on 
    steps: #step we are performing in job 
      - name: printing greeting #name of steps 
        run: echo "Hie my First workflow"
      
      - name: printing bye
        run: echo "good bye..!"
